@startuml
skinparam monochrome true
skinparam defaultFontName PTSerif
skinparam defaultFontSize 12
skinparam TitleFontSize 20

title **Концептуальная структура модели**

' При обновлении диаграммы необходимо регенировать ссылку на неё.

class "Объект недвижимости"
{
    Ид
    ==
    Родительский Ид
    КН
    Наименование
    Назначение
    Вид
    Примечание
}

class "Конструктивный элемент"
{
    Ид
    ==
    Объект недвижимости Ид (FK)
    Полное наименование
    Тип конструктивного элемента
    Подпись на карте    
    Источник информации о геометрии
    Примечание
    --
    Геометрия
}

class Трубопровод
{
    Ид(FK)
    --
    ...
}

class Дорога
{
    Ид(FK)
    --
    ... 
}

class Кабель
{
    Ид(FK)
    --
    ...
}

class "иной"
{
    Ид(FK)
    --
    ...
}

class Сооружение
{
    Ид(FK)
    --
    Тип характеристики
    Величина характеристики
}

class Здание
{
    Ид(FK)
    --
    Площадь
    Этажность
    Материалы стен
}

class ОНС
{
    Ид(FK)
    --
    Степень готовности
}

<> diamond
<> diamondd

"Объект недвижимости" "1" o-- "1..*" "Конструктивный элемент"
"Объект недвижимости" "1" o-- "0..*" "Объект недвижимости"


"Конструктивный элемент" <|--  diamond
diamond -- Трубопровод
diamond -- Дорога
diamond -- Кабель
diamond -- иной

"Объект недвижимости" <|--  diamondd
diamondd -- Сооружение
diamondd -- Здание
diamondd -- ОНС

@enduml